# Generated by Django 5.0 on 2025-12-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_researcher', '0002_superresearcher_is_active_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='superresearcher',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='superresearcher',
            name='lead_class',
            field=models.CharField(choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('Growing Interest', 'Growing Interest'), ('Leading', 'Leading'), ('Dying', 'Dying'), ('Converted', 'Converted'), ('Cold', 'Cold')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='superresearcher',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
