# Generated by Django 5.2.8 on 2025-11-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='rating',
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_class',
            field=models.CharField(blank=True, choices=[('new', 'New Lead'), ('growing_interest', 'Growing Interest'), ('leading', 'Leading'), ('dying', 'Dying'), ('converted', 'Converted'), ('cold', 'Cold')], default='new', max_length=20),
        ),
    ]
