# Generated by Django 5.2.8 on 2025-11-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_contact_rating_contact_lead_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='Full_name',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='lead_class',
            field=models.CharField(blank=True, choices=[('new', 'New Lead'), ('growing_interest', 'Growing Interest'), ('leading', 'Leading'), ('dying', 'Dying'), ('converted', 'Converted'), ('cold', 'Cold')], default='new', max_length=20, null=True),
        ),
    ]
