# Generated by Django 5.2.8 on 2025-11-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contact_first_name_remove_contact_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_class',
            field=models.CharField(blank=True, choices=[('New', 'New Lead'), ('Growing Interest', 'Growing Interest'), ('Leading', 'Leading'), ('Dying', 'Dying'), ('Converted', 'Converted'), ('Cold', 'Cold')], default='new', max_length=20, null=True),
        ),
    ]
