# Generated by Django 5.2.8 on 2025-11-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_sent_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent_emails',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
