# Generated by Django 5.2.8 on 2025-11-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_sent_emails_from_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sent_emails',
            name='body',
        ),
        migrations.AddField(
            model_name='sent_emails',
            name='message',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
