# Generated by Django 5.0 on 2025-12-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_alter_contact_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Apex_Researcher', 'Apex_Researcher'), ('SuperDuperResearcher', 'SuperDuperResearcher')], max_length=20, null=True),
        ),
    ]
