# Generated by Django 5.0 on 2025-12-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_contact_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_by',
        ),
    ]
