# Generated by Django 5.0 on 2025-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_remove_contact_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('ApexResearch', 'ApexResearch'), ('SuperResearcher', 'SuperResearcher')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='lead_class',
            field=models.CharField(choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('Growing Interest', 'Growing Interest'), ('Leading', 'Leading'), ('Dying', 'Dying'), ('Converted', 'Converted'), ('Cold', 'Cold')], default='New', max_length=20),
        ),
    ]
