# Generated by Django 5.0 on 2025-12-04 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_contact_source_alter_contact_lead_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='source',
        ),
    ]
