# Generated by Django 6.0.1 on 2026-01-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sent_sms',
            name='contact',
        ),
        migrations.DeleteModel(
            name='sent_emails',
        ),
        migrations.DeleteModel(
            name='sent_sms',
        ),
    ]
