# Generated by Django 6.0.1 on 2026-01-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apex_research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, null=True)),
                ('website', models.URLField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('promoted', models.BooleanField(default=False)),
                ('is_active_lead', models.BooleanField(default=False)),
                ('lead_class', models.CharField(choices=[('New', 'New Lead'), ('Contacted', 'Contacted'), ('Growing Interest', 'Growing Interest'), ('Leading', 'Leading'), ('Dying', 'Dying'), ('Converted', 'Converted'), ('Cold', 'Cold')], default='New', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
