# Generated by Django 5.0 on 2025-12-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('work', 'Work'), ('personal', 'Personal'), ('urgent', 'Urgent'), ('follow_up', 'Follow-up')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
