# Generated by Django 5.0 on 2025-12-02 05:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
