# Generated by Django 5.0 on 2025-12-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apex_research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, null=True)),
                ('website', models.URLField(null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('promoted', models.BooleanField(default=False)),
            ],
        ),
    ]
