# Generated by Django 5.0 on 2025-12-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apex_research',
            name='is_active_lead',
            field=models.BooleanField(default=False),
        ),
    ]
